source 'https://rubygems.org'

ruby '2.3.1'

gem 'bootstrap-sass', '~> 3.3.6'
gem 'haml'
gem 'devise'
gem 'dotenv-rails'
gem 'html2haml'
gem 'jquery-rails'
gem 'omniauth-google-oauth2'
gem 'pg'
gem 'rails', '5.0.0'
gem 'gretel'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'font-awesome-rails', '~> 4.6', '>= 4.6.3.0'
gem 'carrierwave'
gem 'fog-aws'
gem 'state_machines-activerecord'
gem 'jbuilder'
gem 'bower-rails', '~> 0.10.0'
gem 'material_design_lite-sass'
gem 'puma'
gem 'redis'
gem 'google-api-client', '0.8.6'
gem 'sendgrid'
gem 'initialjs-rails'
gem 'jquery-slick-rails'
gem 'sweetalert-rails'

group :development, :test do
  gem 'seed_dump'
  gem 'rspec-rails'
  gem 'rspec-collection_matchers'
  gem 'byebug'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'spring'
  gem 'factory_girl_rails', '~> 4.0'
  gem 'rubocop'
end

group :production do
  gem 'rails_12factor'
end
