ExerciseSectionTemplate.create!([
  {title: "Commit changes, history and gitignore", goal: nil, content: "Add files and tracking changes.\nAdd files to do-not-track list using .gitignore",  resources: [{"text"=>"Video (3:33 to 8:35)", "url"=>"www.youtube.com/watch?v=Y9XZQO1n_7c"}, {"text"=>"Exercise files", "url"=>"drive.google.com/folderview?id=0B1PtuCWpbEdodnV1M3pTZUhHUWM&usp=sharing "}], track_template_id: 1},
  {title: "Setting up a Git repository", goal: nil, content: "Turning a project/directory to Git repository",  resources: [{"text"=>"Video (till 3:33)", "url"=>"www.youtube.com/watch?v=Y9XZQO1n_7c"}, {"text"=>"Git init", "url"=>"www.atlassian.com/git/tutorials/setting-up-a-repository/git-init"}, {"text"=>"Follow the commands in the video and mail the zipped folder to goutham.pilla@beautifulcode.in   Filename: git_ex_2.zip", "url"=>""}], track_template_id: 1},
  {title: "Why and what is a version control?", goal: nil, content: "Understanding what is a version control and why do we need it.",  resources: [{"text"=>"Quora", "url"=>"www.quora.com/What-is-Git-in-laymans-terms"}, {"text"=>"Better Explained", "url"=>"betterexplained.com/articles/aha-moments-when-learning-git/"}], track_template_id: 1},
  {title: "Branching and Merging", goal: nil, content: "Creating branches and merging.",  resources: [{"text"=>"video (8:34 to 10:45)", "url"=>"www.youtube.com/watch?v=Y9XZQO1n_7c"}, {"text"=>"Exercise files", "url"=>"drive.google.com/folderview?id=0B1PtuCWpbEdodnV1M3pTZUhHUWM&usp=sharing"}], track_template_id: 1},
  {title: "Resolving Merge conflicts", goal: nil, content: "Understanding merge conflicts and resolving them",  resources: [{"text"=>"video (10:43 to 12:55)", "url"=>"www.youtube.com/watch?v=Y9XZQO1n_7c"}, {"text"=>"Exercise files", "url"=>"drive.google.com/folderview?id=0B1PtuCWpbEdodnV1M3pTZUhHUWM&usp=sharing"}], track_template_id: 1},
  {title: "Stashing (Saving your work temporarily)", goal: nil, content: "Saving your un committed work",  resources: [{"text"=>"video (12:55 to 14:24)", "url"=>"www.youtube.com/watch?v=Y9XZQO1n_7c"}, {"text"=>"Exercise files", "url"=>"drive.google.com/folderview?id=0B1PtuCWpbEdodnV1M3pTZUhHUWM&usp=sharing"}], track_template_id: 1},
  {title: "Working with remote repositories", goal: nil, content: "Creating a repo on Github.\nUnderstanding git clone",  resources: [{"text"=>"video (14:24 to 16:00)", "url"=>"www.youtube.com/watch?v=Y9XZQO1n_7c"}, {"text"=>"git clone", "url"=>"www.atlassian.com/git/tutorials/setting-up-a-repository/git-clone/"}], track_template_id: 1},
  {title: "Pull and push from/to repository.", goal: nil, content: "Creating a pull request.",  resources: [{"text"=>"video (16:00 to 17:00)", "url"=>"www.youtube.com/watch?v=Y9XZQO1n_7c"}, {"text"=>"Understanding pull requests", "url"=>"help.github.com/articles/using-pull-requests"}, {"text"=>"Generate SSH-keys and configure Github -1", "url"=>"help.github.com/articles/caching-your-github-password-in-git/#platform-linux"}, {"text"=>"Generate SSH-keys and configure Github -2", "url"=>"help.github.com/articles/generating-ssh-keys/#platform-linux"}], track_template_id: 1},
  {title: "CSS Basics", goal: nil, content: "Go through the links below and understand the concepts.\n\nGetting to know CSS\n  -Types of selectors\n  -Selectors precedence\n  -Combining selectors\n  -Common property values\n",  resources: [{"text"=>"CSS Tutorials #1 - Introduction to CSS and Adding a CSS File to Your HTML", "url"=>"www.youtube.com/watch?v=x9HmYfSN4Gk"}, {"text"=>"CSS Tutorials #2 - CSS syntax and adding color to text", "url"=>"www.youtube.com/watch?v=14JFxpPQC0Q"}, {"text"=>"Getting to know CSS", "url"=>"learn.shayhowe.com/html-css/getting-to-know-css/"}], track_template_id: 3},
  {title: "Adding additional remote repos", goal: nil, content: "Add an additional remote to your learning_git repository",  resources: [{"text"=>"video (17:00 to 17:35)", "url"=>"www.youtube.com/watch?v=Y9XZQO1n_7c"}], track_template_id: 1},
  {title: "Extras", goal: nil, content: "References",  resources: [{"text"=>"git commit messages best practises", "url"=>"robots.thoughtbot.com/5-useful-tips-for-a-better-commit-message"}, {"text"=>"git config, aliases -1", "url"=>"www.atlassian.com/git/tutorials/setting-up-a-repository/git-config"}, {"text"=>"git config, aliases -2", "url"=>"www.atlassian.com/pt/git/tutorial/git-basics#!config"}, {"text"=>"git cheatsheet", "url"=>"training.github.com/kit/downloads/github-git-cheat-sheet.pdf"}], track_template_id: 1},
  {title: "CSS Backgrounds", goal: nil, content: "Styling elements with background properties like setting a color or an image.",  resources: [{"text"=>"CSS Tutorials #3 - Styling Backgrounds", "url"=>"www.youtube.com/watch?v=QqCTmSDY8qI"}, {"text"=>"Styling Background", "url"=>"learn.shayhowe.com/html-css/setting-backgrounds"}], track_template_id: 3},
  {title: "CSS Display properties", goal: nil, content: "How different elements are displayed",  resources: [{"text"=>"CSS Tutorials #12 - DRY Code and grouping and nesting selectors", "url"=>"www.youtube.com/watch?v=tY6JiNHbu2E"}, {"text"=>"CSS Tutorials #14 - Controlling display with display property", "url"=>"www.youtube.com/watch?v=BS35WYv0uuE"}], track_template_id: 3},
  {title: "CSS Typography", goal: nil, content: "Styling paragraphs and texts",  resources: [{"text"=>"CSS Tutorials #4 - How To Style Text", "url"=>"www.youtube.com/watch?v=4ZzLqyJ_qBo"}, {"text"=>"Custom fonts with @font face", "url"=>"www.youtube.com/watch?v=YmxDDSasjX8"}, {"text"=>"Using Google web fonts", "url"=>"www.youtube.com/watch?v=42d1AjNdQG0"}], track_template_id: 3},
  {title: "Complex Selectors", goal: nil, content: "Understand the usage of common selectors, sibling selectors, attribute selectors, psuedo-classes, psuedo-elements",  resources: [{"text"=>"CSS Complex selectors", "url"=>"learn.shayhowe.com/advanced-html-css/complex-selectors/"}, {"text"=>"CSS Tutorials #17 - CSS Pseudo Class selectors", "url"=>"www.youtube.com/watch?v=Uh5loPkHe6E"}, {"text"=>"CSS Tutorials #19 - Child selectors", "url"=>"www.youtube.com/watch?v=KiFo-yKGm6k"}, {"text"=>"CSS Tutorials #26 - Adjacent sibling selectors", "url"=>"www.youtube.com/watch?v=UWzETKG2mYs"}], track_template_id: 3},
  {title: "CSS Positioning", goal: nil, content: "To understand the importance of CSS positioning\nCSS positioning using floats\nCreating reusable elements\nZ-index property\nUnderstand DOM",  resources: [{"text"=>"CSS Tutorials #15 - Positioning Your elements", "url"=>"www.youtube.com/watch?v=g0r1JGjJfY0"}, {"text"=>"CSS Tutorials #16 - Creating a Two Column Layouts with Floats", "url"=>"www.youtube.com/watch?v=X6NV67weCKI"}], track_template_id: 3},
  {title: "CSS Box Model", goal: nil, content: "To understand the importance of CSS box model\nHow to change the size, including width and height of the elements",  resources: [{"text"=>"CSS Tutorials #8 - Box Model - Changing the height and width", "url"=>"www.youtube.com/watch?v=flgW_uuwUIo"}, {"text"=>"CSS Tutorials #9 - Box Model - Margins and how to center a div", "url"=>"www.youtube.com/watch?v=GbmaFuYa5Hg"}, {"text"=>"CSS Tutorials #10 - Box Model - Borders", "url"=>"www.youtube.com/watch?v=kMoHdz4kWqc"}, {"text"=>"CSS Tutorials #11 - Box Model - Padding", "url"=>"www.youtube.com/watch?v=6mdBxWGHQPc"}, {"text"=>"CSS Tutorials #13 - Min and Max width and height to control your elements", "url"=>"www.youtube.com/watch?v=4zHel257P38"}], track_template_id: 3},
  {title: "Responsive Web Design", goal: nil, content: "Understand the importance of responsive web design\nHow to style a web page for multiple screen sizes",  resources: [{"text"=>"Go through the resources below and work on the exercises", "url"=>"learn.shayhowe.com/advanced-html-css/responsive"}], track_template_id: 3},
  {title: "Styling Forms", goal: nil, content: "In the HTML part, we went through the form elements, input types and it’s attributes here we will learn how to style them. You can skip the theory if you are comfortable with the input types and focus on exercise.",  resources: [{"text"=>"Go through the resources below and work on the exercises", "url"=>"learn.shayhowe.com/html-css/building-forms"}], track_template_id: 3},
  {title: "CSS Transforms, Transitions & Animations", goal: nil, content: "Understand the usage of Transforms\nIntroduction to CSS Transitions and Animations",  resources: [{"text"=>"CSS Transforms", "url"=>"learn.shayhowe.com/advanced-html-css/css-transforms"}, {"text"=>"CSS Transitions and Animations", "url"=>"learn.shayhowe.com/advanced-html-css/transitions"}], track_template_id: 3},
  {title: "Performance and Organization", goal: nil, content: "Best practices of writing efficient HTML & CSS",  resources: [{"text"=>"performance", "url"=>"learn.shayhowe.com/advanced-html-css/performance"}, {"text"=>"idiomatic-html", "url"=>"github.com/necolas/idiomatic-html"}, {"text"=>"idiomatic-css", "url"=>"github.com/necolas/idiomatic-css"}], track_template_id: 3},
  {title: "Introduction to HTML", goal: nil, content: "Introduction to HTML\nUnderstanding the basic structure of a Web Page",  resources: [{"text"=>"Go through this link to understand the concepts", "url"=>"developer.mozilla.org/en-US/docs/Web/Guide/HTML/Introduction"}, {"text"=>"Go through this link to understand the basic structure of a Web Page.", "url"=>"www.sitepoint.com/web-foundations/basic-structure-of-a-web-page/"}], track_template_id: 2},
  {title: "HTML Beginner tags", goal: nil, content: "Be familiar with the HTML Tags such as page titles, paragraphs, headings, lists, links, images, tables",  resources: [{"text"=>"Go through the link to understand the concepts", "url"=>"http://htmldog.com/guides/html/beginner"}], track_template_id: 2},
  {title: "HTML Intermediate tags", goal: nil, content: "Be familiar with the HTML Tags such as span, div, blockquote, code, meta, section, dl & dt\n",  resources: [{"text"=>"Go through the link to understand the concepts", "url"=>"http://htmldog.com/guides/html/intermediate"}], track_template_id: 2},
  {title: "HTML - Advanced tags", goal: nil, content: "Be familiar with HTML tags such as time, mark, hr, small, s, u, i, b, sub, sup, conditional comments, thead, tbody, tfoot",  resources: [{"text"=>" Go through the links below to understand the concepts ", "url"=>"http://htmldog.com/guides/html/advanced"}], track_template_id: 2},
  {title: "Introduction to HTML5", goal: nil, content: "Understand what’s new in HTML5\nCreating a simple web page with HTML5\nBasic structure of the web page with HTML5",  resources: [{"text"=>"What is HTML5?", "url"=>"www.youtube.com/watch?v=0aUtQPZcqxE"}, {"text"=>"Starting your first HTML5 site", "url"=>"www.youtube.com/watch?v=sfLBWj5lPgA"}, {"text"=>"Site Structure - Header, Section, Aside & Footer", "url"=>"www.youtube.com/watch?v=DR1upYr2UbA"}, {"text"=>"Creating a simple blog page.", "url"=>"www.youtube.com/watch?v=iPaZ3YJVpv4"}], track_template_id: 2},
  {title: "HTML Forms", goal: nil, content: "Be familiar with various form input types and it’s attributes",  resources: [{"text"=>"Go through the links to understand the concepts mentioned below", "url"=>""}, {"text"=>"Form input types such as number, range, date picker, color picker", "url"=>"www.youtube.com/watch?v=pbm7e-lPGl0"}, {"text"=>"More form input types such as input list, email, telephone, url & search", "url"=>"www.youtube.com/watch?v=9tbTunXSFh4"}], track_template_id: 2},
  {title: "Media elements", goal: nil, content: "Usage of media elements like audio, video and images",  resources: [{"text"=>"Go through the link", "url"=>"learn.shayhowe.com/html-css/adding-media/"}], track_template_id: 2}
])

TrackTemplate.create!([
  {name: "GIT", type: "ExerciseTrackTemplate", image: "Git.png", desc: "A free and open source distributed version control system designed to handle everything from small to very large projects with speed and efficiency"},
  {name: "HTML Fundamentals", type: "ExerciseTrackTemplate", image: "HTML5.png", desc: "HTML, is the standard markup language used to create web pages"},
  {name: "Cascading Style Sheets (CSS)", type: "ExerciseTrackTemplate", image: "css.png", desc: "CSS is a stylesheet language that describes the presentation of an HTML (or XML) document"}
])
